[project]
name = "py-crispr-analyser"
description = "A Python package for analysing the genome for CRISPRs and off-targets"
version = "0.1.0"
license = { text = "MIT" }
readme = "README.md"
authors = [
  {name = "Bo Fussing", email = "bf15@sanger.ac.uk"},
]
requires-python = ">=3.10"
dependencies = []

[tool.pixi.project]
channels = ["conda-forge", "rapidsai"]
platforms = ["linux-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
numba = "==0.61.0"
numpy = ">=2.0,<2.2"

[tool.pixi.dependencies]
black = ">=25.1.0,<26"
flake8 = ">=7.1.2,<8"
pytest = ">=8.3.5,<9"
numba-cuda = ">=0.8.0,<0.9"

[tool.pixi.tasks]
align = "python -m py_crispr_analyser.align"
gather = "python -m py_crispr_analyser.gather"
index = "python -m py_crispr_analyser.index"
search = "python -m py_crispr_analyser.search"

[tool.pixi.target.linux-64.dependencies]
pynvjitlink = ">=0.5.2,<0.6"
cuda-nvcc = ">=12.8.93,<13"
cuda-nvrtc = ">=12.8.93,<13"

[system-requirements]
cuda = ">=12.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.black]
line-length = 80
target-version = ['py310']
