[project]
name = "py-crispr-analyser"
description = "A Python package for analysing the genome for CRISPRs and off-targets"
version = "0.1.0"
license = { text = "MIT" }
readme = "README.md"
authors = [
  {name = "Bo Fussing", email = "bf15@sanger.ac.uk"},
]
requires-python = ">=3.10"
dependencies = [
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
gather = "py_crispr_analyser.gather:run"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
black = "^25.1.0"
flake8 = "^7.1.1"

[tool.black]
line-length = 80
target-version = ['py310']
